// The trust boundary.
//
// This file is the ONLY sanctioned path from network bytes to typed data
// (rule R11). Everything else in the codebase calls into here and nothing
// else parses a frame itself.
//
// The coordinator's entire input surface is attacker-controlled: anyone can
// connect as a worker, that is the product. Three concrete bug shapes live in
// this file's problem space, all with attacker-supplied lengths:
//
//   1. Declared length > frame size      → heap overread (Heartbleed's shape),
//                                          leaks adjacent memory
//   2. Declared length > destination     → heap overflow → potential RCE
//   3. index * kChunkBytes overflows u32 → writes land at a wrong offset
//
// Constraints in this translation unit (docs/CONVENTIONS.md §2):
//   - no raw pointer arithmetic, memcpy, C arrays, or reinterpret_cast
//   - std::span / std::string_view only
//   - every length checked against its kMax* constant BEFORE allocating
//   - checked arithmetic on every attacker-controlled index
//   - never assert() on input — assertions compile out; use a real check
//
// Implement in Phase 1, steps 1.2–1.4. Fuzz it in step 1.5, before moving on.

#include <type_traits>

#include "p2pgpu/protocol/limits.hpp"

// Generated by flatc into the BUILD TREE at build time (R3, step 0.5). Never
// committed, never hand-edited — the schema is the only versioned artifact, so
// this header cannot drift from protocol/p2pgpu.fbs.
#include "p2pgpu/p2pgpu_generated.h"

namespace p2pgpu::protocol {

// ── Step 0.5 build check ────────────────────────────────────────────────
// Proves the generated header is genuinely usable, not merely produced: these
// fail at compile time if flatc did not run, wrote somewhere unexpected, or
// emitted a shape we cannot consume.
//
// Checking the VERIFIER specifically is the point. It is the single sanctioned
// bytes->fields path (R11), so a build where the type exists but the verifier
// is missing would be useless — and would not be noticed until step 1.3.
static_assert(sizeof(p2pgpu::wire::Envelope) > 0,
              "flatc did not generate the root table");

// The verifier is a template (VerifierTemplate<B>), not a plain function, so
// this checks invocability with the concrete flatbuffers::Verifier rather than
// matching an exact signature — which would break on a flatbuffers upgrade for
// no good reason.
static_assert(std::is_invocable_r_v<bool,
                                    decltype(p2pgpu::wire::VerifyEnvelopeBuffer<false>),
                                    ::flatbuffers::Verifier&>,
              "generated verifier is missing or not callable with a Verifier");

// Structs are fixed-layout and inline, so their sizes are part of the wire
// format. If flatc ever lays these out differently the frame decoder's
// assumptions break silently, which is the expensive kind of protocol bug.
static_assert(sizeof(p2pgpu::wire::Uuid) == 16, "Uuid must be two u64");
static_assert(sizeof(p2pgpu::wire::Hash32) == 32, "Hash32 must be four u64");

// The Body union is wire-numbered by declaration order (NONE = 0). Pinning the
// first and last members catches an accidental reorder at COMPILE time rather
// than as mysterious cross-version misrouting. Appending a member moves `Error`
// and will trip this deliberately — when that happens, confirm the change was
// an append, then update the expected value.
static_assert(static_cast<int>(p2pgpu::wire::Body::NONE) == 0);
static_assert(static_cast<int>(p2pgpu::wire::Body::Hello) == 1);
static_assert(static_cast<int>(p2pgpu::wire::Body::Error) == 17,
              "Body union member order changed — this is a WIRE BREAK unless "
              "the change was a pure append (see p2pgpu.fbs)");

// TODO(1.2) ParseHeader(std::span<const std::byte>) -> std::optional<Header>
//
// TODO(1.3) VerifyEnvelope(std::span<const std::byte>) -> Result<const Envelope*>
//
//   Required sequence — deviating from it is a defect even if it appears to
//   work (docs/PROTOCOL.md §1):
//
//     1. size >= kHeaderBytes                    else MalformedMessage
//     2. ParseHeader on a bounds-checked span    else MalformedMessage
//     3. magic == kFrameMagic                    else MalformedMessage
//     4. protocol_ver == kProtocolVersion        else VersionMismatch (fatal)
//     5. fb_len <= kMaxEnvelopeBytes             else PayloadTooLarge
//     6. size >= kHeaderBytes + fb_len           else MalformedMessage
//     7. flatbuffers::Verifier with kMaxVerifyDepth / kMaxVerifyTables
//     8. ONLY NOW may any schema field be read
//
// TODO(1.4) the ten invariants from docs/PROTOCOL.md §4

}  // namespace p2pgpu::protocol
