[package]
name = "p2pgpu-worker-native"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "worker-native"
path = "src/main.rs"

# Phase 4: cargo add wgpu pollster
#          cargo add tokio --features full
#          cargo add tokio-tungstenite clap anyhow tracing tracing-subscriber
[dependencies]
p2pgpu-protocol = { path = "../protocol" }
