#!/usr/bin/env python3
"""Scene generator — step 5.2.

`CONVENTIONS.md` §11 bans committed binary fixtures over 1 MB and says scene
assets are generated by a script. This is that script. What gets committed is
this file plus a few small `.scene` texts; anything larger is produced on
demand.

────────────────────────────────────────────────────────────────────────────
THE FORMAT

Line-based ASCII, one directive per line, `#` to end of line is a comment.
Chosen over JSON/TOML for three reasons that matter here:

  · The C++ side (5.3) parses it with `std::from_chars` and no dependency.
    A scene parser is coordinator-side startup code; adding a JSON library to
    the stack table for it would need a DL5 sign-off (D-0008's stack is
    deliberately short).
  · It diffs. A scene is reviewed by reading it, and a 200-sphere JSON array
    does not survive review.
  · Primitive count scales linearly in bytes with no nesting, so a 10k-primitive
    scene is still a file you can `grep`.

    # comment
    version   1
    camera    origin X Y Z  target X Y Z  up X Y Z  vfov_deg F
    material  <index> lambertian R G B
    material  <index> metal      R G B FUZZ
    material  <index> emissive   R G B
    sphere    CX CY CZ RADIUS MATERIAL
    tri       AX AY AZ  BX BY BZ  CX CY CZ  MATERIAL

Directives may appear in any order EXCEPT that `version` must come first, so a
future v2 parser can reject a file before misreading it. Material indices are
explicit rather than positional — a scene edited by hand should not silently
renumber every primitive when a material is inserted.

────────────────────────────────────────────────────────────────────────────
TRUST BOUNDARY — read this before reusing the parser

**A `.scene` file is TRUSTED in-repo input, exactly like `kernels/manifest.toml`
(D-0030).** It is authored or generated locally, committed, and read at
coordinator startup. It never crosses the network.

**The BVH built from it (5.3) is NOT trusted**, because in Phase 6 the same
bytes arrive from an arbitrary peer. 5.5 hash-verifies and bounds-validates
that, and none of the leniency here may leak into it. Two different files, two
different threat models — do not share a parser between them.

────────────────────────────────────────────────────────────────────────────
DETERMINISM

Same `--seed` ⇒ byte-identical output. Not a nicety: the BVH's BLAKE3 hash is
its content address (5.3/5.4), so a generator that emitted `0.1` one day and
`0.10000000000000001` the next would silently produce a second asset every
build and defeat the cache it feeds. Floats are formatted `%.6f` for that
reason, and `random.Random(seed)` is used rather than the global RNG so an
import elsewhere cannot perturb the stream.
"""

import argparse
import random
import sys

FORMAT_VERSION = 1

# %.6f throughout. Enough for a scene whose extent is single-digit units, and
# FIXED — see the determinism note above.
def f(x: float) -> str:
    return f"{x:.6f}"


def vec(x: float, y: float, z: float) -> str:
    return f"{f(x)} {f(y)} {f(z)}"


def generate(seed: int, sphere_count: int, extent: float) -> list[str]:
    rng = random.Random(seed)
    out: list[str] = []

    out.append(f"# generated by tools/gen_scene.py --seed {seed} "
               f"--spheres {sphere_count} --extent {f(extent)}")
    out.append("# DO NOT EDIT BY HAND — regenerate instead, or the seed in this")
    out.append("# header stops describing the file and the next reader is misled.")
    out.append(f"version {FORMAT_VERSION}")
    out.append("")

    # Camera looks slightly down at the origin from +Z. vfov chosen so the
    # ground plane fills the lower third at this distance.
    out.append(f"camera origin {vec(0.0, 1.4, 4.0)} "
               f"target {vec(0.0, 0.4, 0.0)} "
               f"up {vec(0.0, 1.0, 0.0)} vfov_deg {f(38.0)}")
    out.append("")

    # ── Materials ────────────────────────────────────────────────────────
    # Fixed low indices so a scene stays readable and a diff of two seeds shows
    # only primitives.
    out.append(f"material 0 lambertian {vec(0.72, 0.72, 0.70)}   # ground")
    out.append(f"material 1 metal      {vec(0.88, 0.88, 0.92)} {f(0.02)}  # mirror")
    out.append(f"material 2 emissive   {vec(9.0, 8.4, 7.2)}     # light")
    next_material = 3

    # One coloured lambertian and one rougher metal per palette slot, so the
    # random spheres below have something to point at without inventing a
    # material per primitive (which would bloat the file for no visual gain).
    palette = [
        (0.80, 0.25, 0.25),
        (0.25, 0.55, 0.80),
        (0.35, 0.72, 0.40),
        (0.85, 0.70, 0.25),
        (0.65, 0.35, 0.75),
    ]
    lambert_ids: list[int] = []
    metal_ids: list[int] = []
    for (r, g, b) in palette:
        out.append(f"material {next_material} lambertian {vec(r, g, b)}")
        lambert_ids.append(next_material)
        next_material += 1
    for (r, g, b) in palette:
        out.append(f"material {next_material} metal {vec(r, g, b)} {f(0.18)}")
        metal_ids.append(next_material)
        next_material += 1
    out.append("")

    # ── Ground ───────────────────────────────────────────────────────────
    # Two triangles, not a giant sphere. A huge sphere gives the BVH one
    # primitive whose AABB encloses the entire scene, which defeats every split
    # heuristic at the root and would make 5.3's traversal-depth numbers a lie.
    e = 40.0
    out.append("# ground: two triangles. NOT a large sphere — a primitive whose")
    out.append("# AABB encloses the scene poisons every BVH split above it.")
    out.append(f"tri {vec(-e, 0.0, -e)} {vec(e, 0.0, -e)} {vec(e, 0.0, e)} 0")
    out.append(f"tri {vec(-e, 0.0, -e)} {vec(e, 0.0, e)} {vec(-e, 0.0, e)} 0")
    out.append("")

    # ── Light ────────────────────────────────────────────────────────────
    out.append("# emissive sphere, above and behind the camera's target")
    out.append(f"sphere {vec(2.6, 4.2, 2.2)} {f(1.1)} 2")
    out.append("")

    # ── Anchors ──────────────────────────────────────────────────────────
    out.append("# three fixed anchor spheres, identical for every seed, so two")
    out.append("# scenes can be compared visually without the whole frame moving")
    out.append(f"sphere {vec(0.0, 0.75, 0.0)} {f(0.75)} 1")
    out.append(f"sphere {vec(-1.7, 0.5, 0.35)} {f(0.5)} {lambert_ids[0]}")
    out.append(f"sphere {vec(1.7, 0.5, 0.35)} {f(0.5)} {metal_ids[1]}")
    out.append("")

    # ── Scattered spheres ────────────────────────────────────────────────
    # Rejection-sampled against the anchors so nothing intersects. Intersecting
    # primitives are not a rendering error, but they make a BVH's leaf overlap
    # unrepresentative and this scene exists partly to exercise traversal.
    out.append(f"# {sphere_count} scattered spheres, rejection-sampled to avoid")
    out.append("# overlap so BVH leaf statistics stay representative")
    placed: list[tuple[float, float, float, float]] = [
        (0.0, 0.75, 0.0, 0.75),
        (-1.7, 0.5, 0.35, 0.5),
        (1.7, 0.5, 0.35, 0.5),
        (2.6, 4.2, 2.2, 1.1),
    ]
    attempts = 0
    max_attempts = sphere_count * 200
    while len(placed) - 4 < sphere_count and attempts < max_attempts:
        attempts += 1
        radius = rng.uniform(0.10, 0.30)
        x = rng.uniform(-extent, extent)
        z = rng.uniform(-extent, extent * 0.42)
        y = radius  # resting on the ground plane
        if any((x - px) ** 2 + (y - py) ** 2 + (z - pz) ** 2
               < (radius + pr) ** 2 for (px, py, pz, pr) in placed):
            continue
        placed.append((x, y, z, radius))
        # Two thirds diffuse, one third metal — enough specular to exercise the
        # 5.6 specular path without making the image a hall of mirrors.
        if rng.random() < 0.67:
            mat = rng.choice(lambert_ids)
        else:
            mat = rng.choice(metal_ids)
        out.append(f"sphere {vec(x, y, z)} {f(radius)} {mat}")

    if len(placed) - 4 < sphere_count:
        # Loud, not silent. A scene with fewer primitives than requested would
        # otherwise quietly change every downstream number — BVH depth, the
        # measured F in D-0068, the R5 floor derived from it.
        print(f"WARNING: placed {len(placed) - 4} of {sphere_count} spheres "
              f"after {attempts} attempts; the volume is saturated. "
              f"Reduce --spheres or widen the extent.", file=sys.stderr)

    out.append("")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a p2pgpu .scene file")
    ap.add_argument("--seed", type=int, default=42,
                    help="same seed gives byte-identical output")
    ap.add_argument("--spheres", type=int, default=64,
                    help="scattered spheres, in addition to the fixed anchors")
    # Density, not just count, is the knob that moves BVH traversal depth — and
    # depth is what dominates the uncertainty in D-0068's F estimate. 5.6 needs
    # to measure F across that range rather than at one arbitrary density, so
    # the extent has to be reachable from the command line.
    ap.add_argument("--extent", type=float, default=6.0,
                    help="half-width of the scattered-sphere region; raise it "
                         "for more primitives, lower it for a denser BVH")
    ap.add_argument("-o", "--out", default="-",
                    help="output path, or - for stdout")
    args = ap.parse_args()

    if args.spheres < 0:
        print("--spheres must be >= 0", file=sys.stderr)
        return 2
    if args.extent <= 0.5:
        print("--extent must be > 0.5", file=sys.stderr)
        return 2

    lines = generate(args.seed, args.spheres, args.extent)
    text = "\n".join(lines).rstrip("\n") + "\n"

    if args.out == "-":
        sys.stdout.write(text)
    else:
        # newline="\n" explicitly: on Windows the default would translate to
        # CRLF and change the BLAKE3 content hash of every asset built from it.
        with open(args.out, "w", newline="\n") as fh:
            fh.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
